Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.boot_timeout = 600
  
    config.vm.provider "qemu" do |qe|
      qe.arch = "x86_64"
      qe.machine = "q35"
      qe.cpu = "max"
      qe.net_device = "virtio-net-pci"
      qe.ssh_port = "50022"
    end
  
    # Common provisioning script
    common = <<-SHELL
      sudo apt update -qq 2>&1 >/dev/null
      sudo apt install -y -qq git vim tree net-tools telnet git python3-pip apache2 sshpass nfs-common 2>&1 >/dev/null
      echo "autocmd filetype yaml setlocal ai ts=2 sw=2 et" | sudo tee /home/vagrant/.vimrc
      sudo sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
      sudo systemctl restart sshd
      mkdir -p /opt/homebrew/var/run
      sudo /opt/homebrew/opt/socket_vmnet/bin/socket_vmnet --vmnet-gateway=192.168.42.1 /opt/homebrew/var/run/socket_vmnet
    SHELL
  
    # Provisioning master node
    config.vm.define "nade-la-S" do |master|
      master.vm.hostname = "nade-la-S"
      master.vm.network "private_network", type: "dhcp", ip: "192.168.42.110"
      master.vm.provider "qemu" do |qe|
        qe.ssh_port = "50024"
    
      end
  
      master.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y sudo sshpass
  
        # Disable firewall
        sudo systemctl disable ufw --now
  
        # Set K3s parameters and install K3s
        export INSTALL_K3S_EXEC="--node-ip=192.168.42.110 --flannel-iface=eth1 --tls-san 192.168.42.110 --bind-address=192.168.42.110 --node-external-ip=192.168.42.110 --write-kubeconfig-mode 644"
        curl -sfL https://get.k3s.io | sudo sh -
  
        # Copy K3s node token
        NODE_TOKEN="/var/lib/rancher/k3s/server/node-token"
        sudo cp ${NODE_TOKEN} /vagrant/
  
        # Add alias for kubectl
        echo "alias k='kubectl'" | sudo tee /etc/profile.d/00-aliases.sh
  
        # Install net-tools
        sudo apt-get install -y net-tools

        # Enable firewall
        sudo systemctl enable ufw --now
      SHELL
    end
  
    # Provisioning worker node
    config.vm.define "nade-la-SW" do |worker|
      worker.vm.hostname = "nade-la-SW"
      worker.vm.network "private_network",type: "dhcp", ip: "192.168.42.111"
      worker.vm.provider "qemu" do |qe|
        qe.ssh_port = "50025"
      end    
  
      worker.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y sshpass
  
        # Disable firewalld
        sudo systemctl disable firewalld --now
  
        # Join worker to K3s cluster
        export INSTALL_K3S_EXEC="--node-ip=192.168.42.111 --flannel-iface=eth1 --node-external-ip=192.168.42.111"
        export K3S_URL="https://192.168.42.110:6443"
        export K3S_TOKEN_FILE="/vagrant/node-token"
        curl -sfL https://get.k3s.io | sudo sh -
  
        # Add alias for kubectl
        echo "alias k='kubectl'" | sudo tee /etc/profile.d/00-aliases.sh
  
        # Install net-tools
        sudo apt-get install -y net-tools
      SHELL
    end
  end
  